name: Continuous Integration (CI)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black bandit pytest

      - name: Run Linting (flake8)
        run: flake8 leo/

      - name: Check Code Formatting (Black)
        run: black --check leo/

      - name: Run Security Scan (Bandit)
        run: bandit -r leo/

      - name: Run Tests (Pytest)
        run: pytest

  notify:
    needs: build-and-test
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send Failure Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"CI failed! Check the logs!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

